services:
  #  mongodb:
  # image: mongo:latest
  # container_name: mongodb
  # ports:
  #   - "27017:27017"
  # environment:
  #   MONGO_INITDB_ROOT_USERNAME: admin
  #   MONGO_INITDB_ROOT_PASSWORD: admin
  # volumes:
  #   - ./data:/data/db
  # restart: always
  redis:
   image: redis:latest
   container_name: redis
   ports:
     - "6379:6379"
   restart: always
   volumes:
     - ./data:/data
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: elasticsearch
    restart: always
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: 4194304
        hard: 4194304
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 4g
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"
