apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets.yml
  - mongodb.yml

configMapGenerator:
  - name: mongodb-config
    namespace: tinyx
    literals:
      - MONGODB_PORT=27017
      - MONGODB_HOST=mongodb-svc.tinyx.svc.cluster.local

  - name: mongodb-initdb
    namespace: tinyx
    files:
      - init.js