apiVersion: v1
kind: Secret
stringData:
  password: admin
metadata:
  name: mongodb-admin-credentials
  namespace: tinyx
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: tinyx-gateway-mongodb-credentials  # corresponds to spec.users.passwordSecretRef.name in the MongoDB CRD
  namespace: tinyx
type: Opaque
stringData:
  password: tinyx # corresponds to spec.users.passwordSecretRef.key in the MongoDB CRD

---
apiVersion: v1
kind: Secret
metadata:
  name: tinyx-post-mongodb-credentials  # corresponds to spec.users.passwordSecretRef.name in the MongoDB CRD
  namespace: tinyx
type: Opaque
stringData:
  password: tinyx # corresponds to spec.users.passwordSecretRef.key in the MongoDB CRD

---
apiVersion: v1
kind: Secret
metadata:
  name: tinyx-social-mongodb-credentials  # corresponds to spec.users.passwordSecretRef.name in the MongoDB CRD
  namespace: tinyx
type: Opaque
stringData:
  password: tinyx # corresponds to spec.users.passwordSecretRef.key in the MongoDB CRD

---
apiVersion: v1
kind: Secret
metadata:
  name: tinyx-user-timeline-mongodb-credentials  # corresponds to spec.users.passwordSecretRef.name in the MongoDB CRD
  namespace: tinyx
type: Opaque
stringData:
  password: tinyx # corresponds to spec.users.passwordSecretRef.key in the MongoDB CRD

---
apiVersion: v1
kind: Secret
metadata:
  name: tinyx-home-timeline-mongodb-credentials  # corresponds to spec.users.passwordSecretRef.name in the MongoDB CRD
  namespace: tinyx
type: Opaque
stringData:
  password: tinyx # corresponds to spec.users.passwordSecretRef.key in the MongoDB CRD

---
apiVersion: v1
kind: Secret
metadata:
  name: tinyx-search-mongodb-credentials  # corresponds to spec.users.passwordSecretRef.name in the MongoDB CRD
  namespace: tinyx
type: Opaque
stringData:
  password: tinyx # corresponds to spec.users.passwordSecretRef.key in the MongoDB CRD