apiVersion: v1
kind: Secret
stringData:
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin
metadata:
  name: mongodb-admin-credentials
  namespace: tinyx
type: Opaque

---

apiVersion: v1
kind: Secret
stringData:
  TINYX_GATEWAY_MONGODB_USER: tinyx-gateway
  TINYX_GATEWAY_MONGODB_PASSWORD: tinyx
  TINYX_POST_MONGODB_USER: tinyx-post
  TINYX_POST_MONGODB_PASSWORD: tinyx
  TINYX_SEARCH_MONGODB_USER: tinyx-search
  TINYX_SEARCH_MONGODB_PASSWORD: tinyx
  TINYX_HOME_TIMELINE_MONGODB_USER: tinyx-home-timeline
  TINYX_HOME_TIMELINE_MONGODB_PASSWORD: tinyx
  TINYX_USER_TIMELINE_MONGODB_USER: tinyx-user-timeline
  TINYX_USER_TIMELINE_MONGODB_PASSWORD: tinyx
metadata:
  name: tinyx-mongodb-credentials
  namespace: tinyx
type: Opaque