apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: tinyx
spec:
  selector:
    app: mongodb
  ports:
    - name: mongoport
      port: 27017
      targetPort: 27017
      protocol: TCP