apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: tinyx
  labels:
    app: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - name: mongoport
              containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-credentials
                  key: MONGO_INITDB_ROOT_USERNAME

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-admin-credentials
                  key: MONGO_INITDB_ROOT_PASSWORD

            - name: TINYX_GATEWAY_MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: tinyx-mongodb-credentials
                  key: TINYX_GATEWAY_MONGODB_USER

            - name: TINYX_GATEWAY_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tinyx-mongodb-credentials
                  key: TINYX_GATEWAY_MONGODB_PASSWORD

            - name: TINYX_GATEWAY_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: tinyx-gateway-config
                  key: TINYX_GATEWAY_MONGODB_DATABASE

            - name: TINYX_POST_MONGODB_USER
              valueFrom:
                secretKeyRef:
                  name: tinyx-mongodb-credentials
                  key: TINYX_POST_MONGODB_USER

            - name: TINYX_POST_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tinyx-mongodb-credentials
                  key: TINYX_POST_MONGODB_PASSWORD

            - name: TINYX_POST_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: tinyx-post-config
                  key: TINYX_POST_MONGODB_DATABASE

          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data

            - mountPath: /docker-entrypoint-initdb.d/
              name: init-db

      volumes:
        - name: init-db
          configMap:
            name: mongodb-initdb

  volumeClaimTemplates:
    - metadata:
        name: mongodb-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi