apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - ingress.yml

configMapGenerator:
  - name: tinyx-gateway-config
    namespace: tinyx
    literals:
      - TINYX_GATEWAY_MONGODB_DATABASE=tinyx-gateway

  - name: tinyx-gateway-application-properties
    namespace: tinyx
    files:
      - application.properties