apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: redis-config
    namespace: tinyx
    literals:
      - REDIS_PORT=6379
      - REDIS_HOST=redis.tinyx.svc.cluster.local