apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pod.yml
  - service.yml

configMapGenerator:
  - name: redis-config
    namespace: tinyx
    literals:
      - REDIS_PORT=6379
      - REDIS_HOST=redis.tinyx.svc.cluster.local
    files:
      - redis-config