apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - crds.yaml
  - operator.yaml
  - elastic_search.yml

configMapGenerator:
  - name: elastic-search-config
    namespace: tinyx
    literals:
      - ELASTIC_SEARCH_PORT=9200
      - ELASTIC_SEARCH_HOST=elasticsearch-es-http.tinyx.svc.cluster.local